# Generated by Django 2.1.7 on 2019-05-03 16:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('governate', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('phone_number', models.CharField(default='0', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.png', upload_to='personal/%y/%m/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField()),
                ('image_national_id', models.ImageField(blank=True, null=True, upload_to='national_id/%y%m%d/')),
                ('vehicle', models.CharField(default='car', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), ('phase3', 'phase3')], default='phase1', max_length=7)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captains', to='api.Captain')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_governate', models.CharField(default='Not Specified', max_length=40)),
                ('from_city', models.CharField(default='Not Specified', max_length=40)),
                ('from_address', models.CharField(default='Not Specified', max_length=40)),
                ('to_governate', models.CharField(default='Not Specified', max_length=40)),
                ('to_city', models.CharField(default='Not Specified', max_length=40)),
                ('to_address', models.CharField(default='Not Specified', max_length=40)),
                ('receiver_name', models.CharField(default='Not Specified', max_length=40)),
                ('receiver_phone_number', models.CharField(default='0', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(default='no note', max_length=250)),
                ('duration', models.CharField(default='Not Specified', max_length=50)),
                ('wassally_salary', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('avaliable', 'avaliable'), ('pending', 'pending')], default='avaliable', max_length=10)),
                ('transport_way', models.CharField(choices=[('wassally', 'wassally'), ('other', 'other')], max_length=9)),
                ('to_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('from_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Package'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('package', 'captain')},
        ),
    ]
