# Generated by Django 2.1.7 on 2019-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), (
                'phase3', 'phase3')], default='phase1', max_length=7),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[(
                'avaliable', 'avaliable'), ('accepted', 'accepted')], default='avaliable', max_length=10),
        ),
    ]
