# Generated by Django 2.1.7 on 2019-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190406_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='time_hours',
        ),
        migrations.RemoveField(
            model_name='package',
            name='time_minutes',
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[(
                'avaliable', 'avaliable'), ('pending', 'pending')], default='avaliable', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_day',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
