# Generated by Django 2.1.7 on 2019-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190419_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_day',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
