# Generated by Django 2.1.7 on 2019-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_package_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
