# Generated by Django 2.1.7 on 2019-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package_sender_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='sender_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
