# Generated by Django 2.1.7 on 2019-06-20 18:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190514_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('formated_address', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(
                    null=True, srid=4326, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_address', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('address', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAddress',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromaddress', to='api.Address')),
            ],
        ),









        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='governate',
        ),

        migrations.AlterField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(default='fffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone_number',
            field=models.CharField(default='fffff', max_length=14),
        ),
        migrations.AddField(
            model_name='packageaddress',
            name='package',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='api.Package'),
        ),
        migrations.AddField(
            model_name='packageaddress',
            name='to_address',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toaddress', to='api.Address'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='clients',
            field=models.ManyToManyField(
                through='api.ClientAddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
