# Generated by Django 2.1.7 on 2019-06-15 18:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190514_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governate', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governate', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('receiver_name', models.CharField(max_length=40)),
                ('receiver_phone_number', models.CharField(max_length=14)),
                ('client_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_address', to='api.ClientAddress')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_address', to='api.Package')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='packageaddress',
            unique_together={('client_address', 'package')},
        ),
    ]
