# Generated by Django 2.1.7 on 2019-06-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190615_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_governate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_phone_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_governate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_location',
        ),
    ]
