# Generated by Django 2.1.7 on 2019-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190620_2050'),
    ]

    operations = [

        migrations.AlterField(
            model_name='package',
            name='receiver_phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='packageaddress',
            name='from_address',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='fromaddress', to='api.Address'),
        ),
    ]
