# Generated by Django 2.1.7 on 2019-06-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190620_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_governate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_phone_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_governate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
