# Generated by Django 2.1.7 on 2019-06-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190615_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageaddress',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Package'),
        ),
        migrations.AlterUniqueTogether(
            name='packageaddress',
            unique_together=set(),
        ),
    ]
