# Generated by Django 2.1.7 on 2019-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190616_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='client',
        ),
        migrations.RemoveField(
            model_name='packageaddress',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='packageaddress',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_phone_number',
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone_number',
            field=models.CharField(default='01011760180', max_length=14),
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
        migrations.DeleteModel(
            name='PackageAddress',
        ),
    ]
