# Generated by Django 2.1.7 on 2019-04-23 03:21

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190421_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
