# Generated by Django 2.1.7 on 2019-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190616_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
