# Generated by Django 2.1.7 on 2019-06-16 15:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190616_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governate', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromaddress', to='api.Address')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toaddress', to='api.Address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='clients',
            field=models.ManyToManyField(through='api.ClientAddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
