# Generated by Django 2.1.7 on 2019-04-23 03:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_package_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
        migrations.AddField(
            model_name='package',
            name='from_location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.AddField(
            model_name='package',
            name='to_location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
