# Generated by Django 2.1.7 on 2019-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190620_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='rest_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
