# Generated by Django 2.1.7 on 2019-06-19 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190619_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, unique=True),
        ),
    ]
