# Generated by Django 2.1.7 on 2019-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190621_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='rest_address',
        ),
        migrations.AddField(
            model_name='addressdescription',
            name='address',
            field=models.ManyToManyField(to='api.Address'),
        ),
    ]
