# Generated by Django 2.1.7 on 2019-04-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190424_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='to_location',
        ),
    ]
