# Generated by Django 2.1.7 on 2019-06-21 20:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190621_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdescription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressdescription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='addressdescription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='clients',
        ),
        migrations.AddField(
            model_name='address',
            name='address_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(2, 4), srid=4326),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
        migrations.DeleteModel(
            name='AddressDescription',
        ),
    ]
