# Generated by Django 2.1.7 on 2019-06-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190621_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='client',
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
