# Generated by Django 2.1.7 on 2019-06-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190621_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captains', to='api.Captain'),
        ),
    ]
