# Generated by Django 2.1.7 on 2019-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190622_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sender_phone_number',
            field=models.CharField(default='000', max_length=14),
        ),
    ]
