# Generated by Django 2.1.7 on 2019-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_package_sender_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='sender_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
