# Generated by Django 2.1.7 on 2019-06-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190622_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
    ]
