# Generated by Django 2.1.7 on 2019-06-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190624_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageaddress',
            name='from_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromaddress', to='api.Address'),
        ),
        migrations.AlterField(
            model_name='packageaddress',
            name='to_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toaddress', to='api.Address'),
        ),
    ]
