# Generated by Django 2.1.7 on 2019-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190624_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('shipping', 'shipping'), ('shipped', 'shipped')], default='on_the_way', max_length=11),
        ),
    ]
