# Generated by Django 2.1.7 on 2019-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190630_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('delivered', 'delivered'), ('shipping', 'shipping'), ('shipped', 'shipped')], default='waiting', max_length=11),
        ),
    ]
