# Generated by Django 2.1.7 on 2019-06-30 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190630_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='captain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captains', to='api.Captain'),
        ),
    ]
