# Generated by Django 2.1.7 on 2019-04-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190419_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='time_day',
            new_name='duration',
        ),
    ]
