# Generated by Django 2.1.7 on 2019-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190419_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='transport_way',
            field=models.CharField(choices=[('avaliable', 'avaliable'), ('pending', 'pending')], default='wassally', max_length=9),
        ),
    ]
