# Generated by Django 2.1.7 on 2019-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190420_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='transport_way',
            field=models.CharField(choices=[('wassally', 'wassally'), ('other', 'other')], max_length=9),
        ),
    ]
