# Generated by Django 2.1.7 on 2019-04-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190421_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captains', to='accounts.Captain'),
        ),
    ]
