# Generated by Django 2.1.7 on 2019-02-28 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190224_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('user', models.OneToOneField(on_delete=True, primary_key=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.IntegerField()),
                ('image_national_id', models.ImageField(upload_to='national_id/%y%m%d/')),
                ('feedback', models.CharField(max_length=250)),
            ],
        ),
    ]
