# Generated by Django 2.1.7 on 2019-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190225_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpost',
            name='time',
            field=models.CharField(max_length=40),
        ),
    ]
