# Generated by Django 2.1.7 on 2019-02-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190225_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captains', to='accounts.Captain')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.OrderPOSt', unique=True)),
            ],
        ),
    ]
