# Generated by Django 2.1.7 on 2019-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('w', 'waiting'), ('p', 'progressing'), ('f', 'finished')], default='w', max_length=1),
        ),
    ]
