# Generated by Django 2.1.7 on 2019-02-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delivery_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_money', models.IntegerField()),
                ('orderpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoffers', to='accounts.OrderPOSt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.Captain')),
            ],
        ),
    ]
