# Generated by Django 2.1.7 on 2019-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190225_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='image_national_id',
            field=models.ImageField(blank=True, null=True, upload_to='national_id/%y%m%d/'),
        ),
    ]
