# Generated by Django 2.1.7 on 2019-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190226_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='vehicle',
            field=models.CharField(default='car', max_length=30),
        ),
    ]
