# Generated by Django 2.1.7 on 2019-02-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_captain_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_feedback', to='accounts.Captain')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
