# Generated by Django 2.1.7 on 2019-02-28 14:19

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190228_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to=settings.AUTH_USER_MODEL, validators=[accounts.models.user_not_client]),
        ),
    ]
