# Generated by Django 2.1.7 on 2019-03-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190228_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.OrderPOSt'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('order', 'captain')},
        ),
    ]
