# Generated by Django 2.1.7 on 2019-03-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='feedback',
        ),
    ]
