# Generated by Django 2.1.7 on 2019-03-11 00:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_captain_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.OrderPost'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='orderpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoffers', to='accounts.OrderPost'),
        ),
        migrations.AlterField(
            model_name='orderpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, validators=[accounts.models.user_not_client]),
        ),
    ]
